/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BotonSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Pila = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        botonCola = new javax.swing.JMenuItem();
        botonColaCircular = new javax.swing.JMenuItem();
        Listas = new javax.swing.JMenu();
        botonListaLigada = new javax.swing.JMenuItem();
        botonListaDoblementeLigada = new javax.swing.JMenuItem();
        botonListaOrdenada = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        botonArbol = new javax.swing.JMenuItem();
        botonArbolB = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        botonInsercionDirecta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Estructura de datos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\proyecto\\imagenes\\logomacletras.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(780, 20, 290, 174);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 153, 0));
        jLabel3.setText("Pérez García Víctor Kevin");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 250, 196, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Inicio");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(630, 280, 160, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Proyecto Final Grupo 1351");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 120, 220, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 153, 0));
        jLabel6.setText("Islas López Estefanny");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 280, 171, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 153, 0));
        jLabel7.setText("López Servin Mauricio");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 310, 171, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 153, 0));
        jLabel8.setText("Jiménez González Diego");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 220, 190, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 153, 0));
        jLabel9.setText("Integrantes del equipo:");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 190, 184, 22);

        jButton1.setText("¿Qué son las estructuras de datos?");
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 380, 280, 23);

        jButton2.setText("¿Comó usar el tutorial?");
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 430, 280, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("Tutorial de Estructuras de datos");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 40, 690, 90);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\proyecto\\imagenes\\fonfo.jpg")); // NOI18N
        fondo.setText("jLabel2");
        jPanel1.add(fondo);
        fondo.setBounds(10, 10, 1280, 920);

        jMenu1.setText("Archivo");

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jMenu1.add(BotonSalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Estructuras de datos lineales");

        Pila.setText("Pila");
        Pila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilaActionPerformed(evt);
            }
        });
        jMenu3.add(Pila);

        jMenu5.setText("Cola");

        botonCola.setText("Cola");
        botonCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColaActionPerformed(evt);
            }
        });
        jMenu5.add(botonCola);

        botonColaCircular.setText("Cola circular");
        botonColaCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColaCircularActionPerformed(evt);
            }
        });
        jMenu5.add(botonColaCircular);

        jMenu3.add(jMenu5);

        Listas.setText("Listas");

        botonListaLigada.setText("Lista ligada");
        botonListaLigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaLigadaActionPerformed(evt);
            }
        });
        Listas.add(botonListaLigada);

        botonListaDoblementeLigada.setText("Lista doblemente ligada");
        botonListaDoblementeLigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaDoblementeLigadaActionPerformed(evt);
            }
        });
        Listas.add(botonListaDoblementeLigada);

        botonListaOrdenada.setText("Lista ordenada");
        botonListaOrdenada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaOrdenadaActionPerformed(evt);
            }
        });
        Listas.add(botonListaOrdenada);

        jMenu3.add(Listas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Estructuras de datos no lineales");

        jMenu7.setText("Arboles");

        botonArbol.setText("Arbol binario ");
        botonArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArbolActionPerformed(evt);
            }
        });
        jMenu7.add(botonArbol);

        botonArbolB.setText("Arbol B");
        botonArbolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArbolBActionPerformed(evt);
            }
        });
        jMenu7.add(botonArbolB);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        jMenu8.setText("Algoritmos de ordenación");

        jMenu2.setText("Ordenación por vector");

        botonInsercionDirecta.setText("Insercion directa");
        botonInsercionDirecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsercionDirectaActionPerformed(evt);
            }
        });
        jMenu2.add(botonInsercionDirecta);

        jMenuItem1.setText("Inserción Binaria");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem8.setText("Selección directa");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Intercambio directo (burbuja)");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem2.setText("Sacudida");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Shell");
        jMenu2.add(jMenuItem3);

        jMenuItem10.setText("Ordenación segun arbol (HeapSort)");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText(" Ordenación por partición (Quicksort)");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenu8.add(jMenu2);

        jMenu6.setText("Ordenación por archivos ");

        jMenuItem4.setText("Mezcla directa (mergue sort)");
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Mezcla natural ");
        jMenu6.add(jMenuItem5);

        jMenu8.add(jMenu6);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void PilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilaActionPerformed
        // TODO add your handling code here:
        Ejecutor ventana = new Ejecutor("pila","pila.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_PilaActionPerformed

    private void botonColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColaActionPerformed
        // TODO add your handling code here:
        Ejecutor ventana = new Ejecutor("cola","cola.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_botonColaActionPerformed

    private void botonArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArbolActionPerformed
        EjecutorUnico ventana = new EjecutorUnico("arbol","arbol.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_botonArbolActionPerformed

    private void botonColaCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColaCircularActionPerformed
        // TODO add your handling code here:
        Ejecutor ventana = new Ejecutor("colaCircular","cola.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_botonColaCircularActionPerformed

    private void botonListaLigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaLigadaActionPerformed
        // TODO add your handling code here:
        Ejecutor ventana = new Ejecutor("listaLigada","lista.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_botonListaLigadaActionPerformed

    private void botonListaDoblementeLigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaDoblementeLigadaActionPerformed
        // TODO add your handling code here:
        Ejecutor ventana = new Ejecutor("listaDoblementeLigada","lista.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_botonListaDoblementeLigadaActionPerformed

    private void botonListaOrdenadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaOrdenadaActionPerformed
        // TODO add your handling code here:
        Ejecutor ventana = new Ejecutor("listaOrdenada","lista.jpg");
            ventana.setVisible(true);
    }//GEN-LAST:event_botonListaOrdenadaActionPerformed

    private void botonArbolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArbolBActionPerformed
        // TODO add your handling code here:
         EjecutorUnico ventana = new EjecutorUnico("arbolB","arbolB.jpg");
           ventana.setVisible(true);
    }//GEN-LAST:event_botonArbolBActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        EjecutorUnico ventana = new EjecutorUnico("quicksort","insercionDirecta.jpg");
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        EjecutorUnico ventana = new EjecutorUnico("burbuja","insercionDirecta.jpg");
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void botonInsercionDirectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsercionDirectaActionPerformed
        EjecutorUnico ventana = new EjecutorUnico("insercionDirecta","insercionDirecta.jpg");
        ventana.setVisible(true);
    }//GEN-LAST:event_botonInsercionDirectaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BotonSalir;
    private javax.swing.JMenu Listas;
    private javax.swing.JMenuItem Pila;
    private javax.swing.JMenuItem botonArbol;
    private javax.swing.JMenuItem botonArbolB;
    private javax.swing.JMenuItem botonCola;
    private javax.swing.JMenuItem botonColaCircular;
    private javax.swing.JMenuItem botonInsercionDirecta;
    private javax.swing.JMenuItem botonListaDoblementeLigada;
    private javax.swing.JMenuItem botonListaLigada;
    private javax.swing.JMenuItem botonListaOrdenada;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
