/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.text.Document;

/**
 *
 * @author diego
 */
public class Ejecutor extends javax.swing.JFrame {

    /**
     * Creates new form Ejecutor
     * @param teoria
     * @param imagen
     * @param ejecutable
     */
    Archivo a;
    String texto;
    String imagen;
    int num;
    String codigo;
    
    public Ejecutor(String codigo, String imagen) {
        a=new Archivo();
        this.imagen=imagen;
        this.codigo=codigo;
        num=1;
        texto=a.leer("C://proyecto/teoria/"+codigo+".txt");       
        initComponents();        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoDato = new javax.swing.ButtonGroup();
        grupotextio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botonEjecutor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonInt = new javax.swing.JRadioButton();
        botonChar = new javax.swing.JRadioButton();
        botonFloat = new javax.swing.JRadioButton();
        botonTeoria = new javax.swing.JRadioButton();
        botonCodigo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CuadroTexto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ejecutor");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1254, 618));
        jPanel1.setMinimumSize(new java.awt.Dimension(1254, 618));
        jPanel1.setLayout(null);

        botonEjecutor.setText("Ejecutar código");
        botonEjecutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutorActionPerformed(evt);
            }
        });
        jPanel1.add(botonEjecutor);
        botonEjecutor.setBounds(914, 480, 170, 23);

        jButton2.setText("Cerrar ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(914, 519, 170, 23);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\proyecto\\imagenes\\"+imagen));
            jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
            jLabel1.setMinimumSize(new java.awt.Dimension(400, 400));
            jLabel1.setPreferredSize(new java.awt.Dimension(400, 400));
            jPanel1.add(jLabel1);
            jLabel1.setBounds(785, 42, 400, 400);

            botonInt.setBackground(new java.awt.Color(0, 0, 0));
            grupoTipoDato.add(botonInt);
            botonInt.setForeground(new java.awt.Color(255, 255, 255));
            botonInt.setSelected(true);
            botonInt.setText("int");
            botonInt.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonIntActionPerformed(evt);
                }
            });
            jPanel1.add(botonInt);
            botonInt.setBounds(797, 482, 70, 23);

            botonChar.setBackground(new java.awt.Color(0, 0, 0));
            grupoTipoDato.add(botonChar);
            botonChar.setForeground(new java.awt.Color(255, 255, 255));
            botonChar.setText("char");
            botonChar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonCharActionPerformed(evt);
                }
            });
            jPanel1.add(botonChar);
            botonChar.setBounds(797, 505, 70, 23);

            botonFloat.setBackground(new java.awt.Color(0, 0, 0));
            grupoTipoDato.add(botonFloat);
            botonFloat.setForeground(new java.awt.Color(255, 255, 255));
            botonFloat.setText("float");
            botonFloat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonFloatActionPerformed(evt);
                }
            });
            jPanel1.add(botonFloat);
            botonFloat.setBounds(797, 528, 70, 23);

            botonTeoria.setBackground(new java.awt.Color(0, 0, 0));
            grupotextio.add(botonTeoria);
            botonTeoria.setForeground(new java.awt.Color(255, 255, 255));
            botonTeoria.setSelected(true);
            botonTeoria.setText("teoría");
            botonTeoria.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonTeoriaActionPerformed(evt);
                }
            });
            jPanel1.add(botonTeoria);
            botonTeoria.setBounds(357, 532, 57, 23);

            botonCodigo.setBackground(new java.awt.Color(0, 0, 0));
            grupotextio.add(botonCodigo);
            botonCodigo.setForeground(new java.awt.Color(255, 255, 255));
            botonCodigo.setText("código");
            botonCodigo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonCodigoActionPerformed(evt);
                }
            });
            jPanel1.add(botonCodigo);
            botonCodigo.setBounds(357, 558, 100, 23);

            CuadroTexto.setEditable(false);
            CuadroTexto.setColumns(20);
            CuadroTexto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            CuadroTexto.setRows(5);
            CuadroTexto.setText(texto);
            CuadroTexto.setAutoscrolls(false);
            CuadroTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
            CuadroTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            CuadroTexto.setMaximumSize(new java.awt.Dimension(222, 77));
            CuadroTexto.setMinimumSize(new java.awt.Dimension(222, 77));
            CuadroTexto.setSelectionColor(new java.awt.Color(0, 102, 204));
            jScrollPane2.setViewportView(CuadroTexto);

            jPanel1.add(jScrollPane2);
            jScrollPane2.setBounds(36, 42, 693, 472);

            jLabel2.setBackground(new java.awt.Color(255, 255, 255));
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("Selección de código:");
            jPanel1.add(jLabel2);
            jLabel2.setBounds(785, 460, 97, 14);

            jLabel3.setIcon(new javax.swing.ImageIcon("C:\\proyecto\\imagenes\\FondoEjecutor.jpg")); // NOI18N
            jPanel1.add(jLabel3);
            jLabel3.setBounds(0, 0, 1250, 720);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botonEjecutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutorActionPerformed
        Runtime app = Runtime.getRuntime();
        try{
            System.out.println("ya1");
            app.exec("cmd.exe /k start C://proyecto/codigos/"+num+codigo+".exe"); 
            System.out.println("ya2");
        }catch(Exception e){
            System.out.println("ya3");
        }
    }//GEN-LAST:event_botonEjecutorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntActionPerformed
        num=1;
        actualizaTexto();
    }//GEN-LAST:event_botonIntActionPerformed

    private void botonTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTeoriaActionPerformed
        texto=a.leer("C://proyecto/teoria/"+codigo+".txt");
        CuadroTexto.setText(texto);
    }//GEN-LAST:event_botonTeoriaActionPerformed

    private void botonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCodigoActionPerformed
        actualizaTexto();
    }//GEN-LAST:event_botonCodigoActionPerformed

    private void botonCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCharActionPerformed
        num=2;
        actualizaTexto();
    }//GEN-LAST:event_botonCharActionPerformed

    private void botonFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFloatActionPerformed
        num=3;
        actualizaTexto();
    }//GEN-LAST:event_botonFloatActionPerformed
    
    private void actualizaTexto(){
        botonCodigo.setSelected(true);
        texto=a.leer("C://proyecto/codigos/"+num+codigo+".cpp");
        CuadroTexto.setText(texto);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CuadroTexto;
    private javax.swing.JRadioButton botonChar;
    private javax.swing.JRadioButton botonCodigo;
    private javax.swing.JButton botonEjecutor;
    private javax.swing.JRadioButton botonFloat;
    private javax.swing.JRadioButton botonInt;
    private javax.swing.JRadioButton botonTeoria;
    private javax.swing.ButtonGroup grupoTipoDato;
    private javax.swing.ButtonGroup grupotextio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
